clear, clc

mainPath = '/home/wescomp/data/ALS_DVS_Dataset/'

checkpointPath = [mainPath 'network_checkpoints' filesep];

if ~exist(checkpointPath, 'dir')
    mkdir(checkpointPath)
end

imageStore = imageDatastore([mainPath 'features' filesep],...
    'IncludeSubfolders',true,'FileExtensions','.nii','LabelSource','foldernames','ReadFcn',@(x) readNifti_ncars(x,1:6,false));

[testImageStore,trainImageStore] = splitEachLabel(imageStore,0.2,'randomized'); %orig paper used 80/20 split

numTest = numel(testImageStore.Files)
numTrain = numel(trainImageStore.Files)

makePretrainedNetworkGoogleNet_3d_als_dvs

%CNN
miniBatchSize  = 2^6;
validationFrequency = floor(numTrain/miniBatchSize);
options = trainingOptions('adam', ...
    'MiniBatchSize',miniBatchSize, ...
    'MaxEpochs',24, ...
    'InitialLearnRate',1e-4, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.5, ...
    'LearnRateDropPeriod',6, ...
    'ValidationData',testImageStore, ...
    'ValidationFrequency',validationFrequency, ...
    'Shuffle','every-epoch', ...
    'Plots','training-progress', ...
    'ResetInputNormalization', false, ...
    'CheckpointPath',checkpointPath,...
    'DispatchInBackground',true,...
    'Verbose',true);

[net,info] = trainNetwork(trainImageStore, lgraph, options);

[YPred,probs] = classify(net,testImageStore);
accuracy = mean(YPred == testImageStore.Labels)

save('trainedNetworks/googlenet_3d_alsdvs_noaugmentation_9963acc_v1.mat','net')
