function layers = makeDHP19network()

layers = [
    imageInputLayer([256 256 10],"Name","imageinput",'Normalization','zscore')
    convolution2dLayer([3 3],32,"Name","conv_1","Padding","same")
    batchNormalizationLayer("Name","BN1")
    reluLayer("Name","relu_1")
    maxPooling2dLayer([2 2],"Name","maxpool_1","Padding","same","Stride",[2 2])
    convolution2dLayer([3 3],64,"Name","conv_2","Padding","same")
    batchNormalizationLayer("Name","BN2")
    reluLayer("Name","relu_2")
    dropoutLayer(0.5)
    convolution2dLayer([3 3],64,"Name","conv_3","Padding","same")
    batchNormalizationLayer("Name","BN3")
    reluLayer("Name","relu_3")
    convolution2dLayer([3 3],64,"Name","conv_4","Padding","same")
    batchNormalizationLayer("Name","BN4")
    reluLayer("Name","relu_4")
    maxPooling2dLayer([2 2],"Name","maxpool_2","Padding","same","Stride",[2 2])
    convolution2dLayer([3 3],128,"Name","conv_5","DilationFactor",[2 2],"Padding","same")
    batchNormalizationLayer("Name","BN5")
    reluLayer("Name","relu_5")
    dropoutLayer(0.5)
    convolution2dLayer([3 3],128,"Name","conv_6","DilationFactor",[2 2],"Padding","same")
    batchNormalizationLayer("Name","BN6")
    reluLayer("Name","relu_6")
    convolution2dLayer([3 3],128,"Name","conv_7","DilationFactor",[2 2],"Padding","same")
    batchNormalizationLayer("Name","BN7")
    reluLayer("Name","relu_7")
    convolution2dLayer([3 3],128,"Name","conv_8","DilationFactor",[2 2],"Padding","same")
    batchNormalizationLayer("Name","BN8")
    reluLayer("Name","relu_8")
    transposedConv2dLayer([3 3],64,"Name","transposed-conv_1","Cropping","same","Stride",[2 2])
    batchNormalizationLayer("Name","BN9")
    reluLayer("Name","relu_9")
    dropoutLayer(0.5)
    convolution2dLayer([3 3],64,"Name","conv_9","DilationFactor",[2 2],"Padding","same")
    batchNormalizationLayer("Name","BN10")
    reluLayer("Name","relu_10")
    convolution2dLayer([3 3],64,"Name","conv_10","DilationFactor",[2 2],"Padding","same")
    batchNormalizationLayer("Name","BN11")
    reluLayer("Name","relu_11")
    convolution2dLayer([3 3],64,"Name","conv_11","DilationFactor",[2 2],"Padding","same")
    batchNormalizationLayer("Name","BN12")
    reluLayer("Name","relu_12")
    convolution2dLayer([3 3],64,"Name","conv_12","DilationFactor",[2 2],"Padding","same")
    batchNormalizationLayer("Name","BN13")
    reluLayer("Name","relu_13")
    transposedConv2dLayer([3 3],32,"Name","transposed-conv_2","Cropping","same","Stride",[2 2])
    batchNormalizationLayer("Name","BN14")
    reluLayer("Name","relu_14")
    dropoutLayer(0.5)
    convolution2dLayer([3 3],32,"Name","conv_13","Padding","same")
    batchNormalizationLayer("Name","BN15")
    reluLayer("Name","relu_15")
    %     dropoutLayer(0.2)
    convolution2dLayer([1 1],13,"Name","conv_14","Padding","same")
    regressionLayer("Name","regressionoutput")];
