function imu = readUAVimu(fn)

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/wescomp/Dropbox/WesDocs/UD/Research/eventCameraFeatures/uavData/events.txt
%
% Auto-generated by MATLAB on 04-Jan-2021 11:57:37

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["id", "timestamp", "gyroX", "gyroY", "gyroZ", "accelX", "accelY", "accelZ"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
events = readtable(fn, opts);


%% Clear temporary variables
clear opts

imu.timeStamp = events.timestamp.*1e6;
imu.gyroX = events.gyroX;
imu.gyroY = events.gyroY;
imu.gyroZ = events.gyroZ;
imu.accelX = events.accelX;
imu.accelY = events.accelY;
imu.accelZ = events.accelZ;

