function aedat = rollingVec2Frames(aedat)

%Converts 1D vectors from rolling shutter into 2D images

%First move rolling shutter images into sub field
aedat.data.frameRolling = aedat.data.frame;
aedat.data.frame = [];

%Group by reset/read, time, xposition
% frameBreaks = aedat.data.frameRolling.xPosition==0 & aedat.data.frameRolling.yPosition==0 & aedat.data.frameRolling.reset==0;
% frameBreaks = cellfun(@numel, aedat.data.frameRolling.samples)>180;
% frameBreaks = diff(cat(1,-Inf,frameBreaks))==-1;

aedat.data.frame.samples{1} = nan(180,240);
aedat.data.frame.resetStartTime{1} = nan(180,240);
aedat.data.frame.resetEndTime{1} = nan(180,240);
aedat.data.frame.readStartTime{1} = nan(180,240);
aedat.data.frame.readEndTime{1} = nan(180,240);
for vLoop = 1:aedat.data.frameRolling.numEvents
    %Add another frame???
%     if frameBreaks(vLoop)
%         if max(aedat.data.frame.sample{end}(:) ~= 0)
%             aedat.data.frame.sample{end+1} = zeros(180,240);
%         end
%     end
    if aedat.data.frameRolling.reset(vLoop)
        %add value
        aedat.data.frame.samples{end}(...
            [aedat.data.frameRolling.yPosition(vLoop)+1:...
            aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],...
            [aedat.data.frameRolling.xPosition(vLoop)+1:...
            aedat.data.frameRolling.xPosition(vLoop)+aedat.data.frameRolling.xLength(vLoop)]) = ...
            nansum(cat(3,...
            aedat.data.frame.samples{end}(...
            [aedat.data.frameRolling.yPosition(vLoop)+1:...
            aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],...
            [aedat.data.frameRolling.xPosition(vLoop)+1:...
            aedat.data.frameRolling.xPosition(vLoop)+aedat.data.frameRolling.xLength(vLoop)])...
            ,...
            aedat.data.frameRolling.samples{vLoop}),3);
        aedat.data.frame.resetStartTime{end}(...
            [aedat.data.frameRolling.yPosition(vLoop)+1:...
            aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],...
            [aedat.data.frameRolling.xPosition(vLoop)+1:...
            aedat.data.frameRolling.xPosition(vLoop)+aedat.data.frameRolling.xLength(vLoop)]) = ...
            aedat.data.frameRolling.timeStampStart(vLoop);
        aedat.data.frame.resetEndTime{end}(...
            [aedat.data.frameRolling.yPosition(vLoop)+1:...
            aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],...
            [aedat.data.frameRolling.xPosition(vLoop)+1:...
            aedat.data.frameRolling.xPosition(vLoop)+aedat.data.frameRolling.xLength(vLoop)]) = ...
            aedat.data.frameRolling.timeStampEnd(vLoop);

    else
        %subtract alue
%         aedat.data.frame.sample{end}([aedat.data.frameRolling.yPosition(vLoop)+1:aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],[aedat.data.frameRolling.xPosition(vLoop)+1:aedat.data.frameRolling.xLength(vLoop)]) = ...
%             aedat.data.frame.sample{end}([aedat.data.frameRolling.yPosition(vLoop)+1:aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],aedat.data.frameRolling.xPosition(vLoop)+1) - ...
%             aedat.data.frameRolling.samples{vLoop};
        aedat.data.frame.samples{end}(...
            [aedat.data.frameRolling.yPosition(vLoop)+1:...
            aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],...
            [aedat.data.frameRolling.xPosition(vLoop)+1:...
            aedat.data.frameRolling.xPosition(vLoop)+aedat.data.frameRolling.xLength(vLoop)]) = ...
            nansum(cat(3,...
            aedat.data.frame.samples{end}(...
            [aedat.data.frameRolling.yPosition(vLoop)+1:...
            aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],...
            [aedat.data.frameRolling.xPosition(vLoop)+1:...
            aedat.data.frameRolling.xPosition(vLoop)+aedat.data.frameRolling.xLength(vLoop)])...
            ,-1.*...
            aedat.data.frameRolling.samples{vLoop}),3);
        aedat.data.frame.readStartTime{end}(...
            [aedat.data.frameRolling.yPosition(vLoop)+1:...
            aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],...
            [aedat.data.frameRolling.xPosition(vLoop)+1:...
            aedat.data.frameRolling.xPosition(vLoop)+aedat.data.frameRolling.xLength(vLoop)]) = ...
            aedat.data.frameRolling.timeStampStart(vLoop);
        aedat.data.frame.readEndTime{end}(...
            [aedat.data.frameRolling.yPosition(vLoop)+1:...
            aedat.data.frameRolling.yPosition(vLoop)+aedat.data.frameRolling.yLength(vLoop)],...
            [aedat.data.frameRolling.xPosition(vLoop)+1:...
            aedat.data.frameRolling.xPosition(vLoop)+aedat.data.frameRolling.xLength(vLoop)]) = ...
            aedat.data.frameRolling.timeStampEnd(vLoop);
    end
    if aedat.data.frameRolling.lastData(vLoop)
        if max(aedat.data.frame.samples{end}(:) ~= 0)
            aedat.data.frame.samples{end+1} = nan(180,240);
            aedat.data.frame.resetStartTime{end+1} = nan(180,240);
            aedat.data.frame.resetEndTime{end+1} = nan(180,240);
            aedat.data.frame.readStartTime{end+1} = nan(180,240);
            aedat.data.frame.readEndTime{end+1} = nan(180,240);
        end
    end
%     imagesc(aedat.data.frame.sample{end})
end

